MESSAGE_CONTENT_LENGTH = "ConLen"
MESSAGE_ACTION = "Action"
MESSAGE_CODE_INFORMATION = "InfCode"

MESSAGE_ACTIONLOGIN_Code = "1"
MESSAGE_ACTIONLOGIN_Login = "Login"
MESSAGE_ACTIONLOGIN_Password = "Password"
MESSAGE_ACTIONLOGIN_Token = "Token"
