MESSAGE_CONTENT_LENGTH = "ConLen"
MESSAGE_ACTION = "Action"
MESSAGE_STATUS = "Status"
MESSAGE_STATUS_OK = "OK"

MESSAGE_ACTION_LOGIN_CODE = "1"
MESSAGE_ACTION_LOGIN_LOGIN = "Login"
MESSAGE_ACTION_LOGIN_PASSWORD = "Password"
MESSAGE_ACTION_LOGIN_TOKEN = "Token"

MESSAGE_ACTION_REGISTER_CODE = "2"
MESSAGE_ACTION_REGISTER_LOGIN = "Login"
MESSAGE_ACTION_REGISTER_PASSWORD = "Password"

MESSAGE_ACTION_NEW_ROOM_CODE = "3"
MESSAGE_ACTION_NEW_ROOM_ROOM_NAME = "RoomName"
MESSAGE_ACTION_NEW_ROOM_USER_TOKEN = "Token"

MESSAGE_ACTION_JOIN_ROOM_CODE = "4"
MESSAGE_ACTION_JOIN_ROOM_ROOM_NAME = "RoomName"
MESSAGE_ACTION_JOIN_ROOM_USER_TOKEN = "Token"

MESSAGE_ACTION_LISTROOMS_CODE = "5"
MESSAGE_ACTION_LISTROOMS_LIST = "RoomsList"

MESSAGE_ACTION_LEAVEROOM_CODE = "6"

MESSAGE_ACTION_LISTUSERS_CODE = "7"
MESSAGE_ACTION_LISTUSERS_LIST = "UsersList"

MESSAGE_ACTION_SENDMESSAGE_CODE = "8"
MESSAGE_ACTION_SENDMESSAGE_NAME = "Message"
MESSAGE_ACTION_SENDMESSAGE_TOKEN = "Token"

MESSAGE_ACTION_LOGOUT_CODE = "9"

MESSAGE_ACTION_RECVMESSAGE_CODE = "10"
