MESSAGE_CONTENT_LENGTH = "ConLen"
MESSAGE_ACTION = "Action"
MESSAGE_STATUS = "Status"
MESSAGE_STATUS_OK = "OK"

MESSAGE_ACTIONLOGIN_Code = "1"
MESSAGE_ACTIONLOGIN_Login = "Login"
MESSAGE_ACTIONLOGIN_Password = "Password"
MESSAGE_ACTIONLOGIN_Token = "Token"

MESSAGE_ACTIONREGISTER_Code = "2"
MESSAGE_ACTIONREGISTER_Login = "Login"
MESSAGE_ACTIONREGISTER_Password = "Password"
